### PR TITLE
PIE-558: restyling Dough Staking UI

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

### CODE REVIEW

**Comment by Alexintosh** [comment]
Screenshot 2021-11-10 at 15 10 10
Screenshot 2021-11-10 at 15 10 05

**Comment by TotoFullStackDev** [comment]
@Alexintosh fixed.

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
**What I tested and passed:**
User with wallet not connected:
* All pages work as expected, including the PIE pages, the dough-staking + dough-staking campaign + kpi-options-campaign + dough + slice
* Simulator and permalink work well
* Wallet connection works well

User with wallet connected:
* Besides the errors below, Piefolio and dough-staking pages show the right information
* Slice page allows redemption (can't test the whole process, due to lack of slice)
* Status modals respond accordingly and show the proper information

**What did not pass testing:**
1. User on /dough-staking with no wallet logged can't see the  Key Stats counting down. It starts when the user is connected
https://www.loom.com/share/2d371c5939cf49a3b9a5132e6b4de42e

2. In /piefolio the governance information is not updated, it is currently showing closed votes only from october (same un mainnet)
image
 
3. Your holding numbers are shown Green even though they are negative
image

**Comment by TotoFullStackDev** [comment]
> **What I tested and passed:** User with wallet not connected:
> 
> * All pages work as expected, including the PIE pages, the dough-staking + dough-staking campaign + kpi-options-campaign + dough + slice
> * Simulator and permalink work well
> * Wallet connection works well
> 
> User with wallet connected:
> 
> * Besides the errors below, Piefolio and dough-staking pages show the right information
> * Slice page allows redemption (can't test the whole process, due to lack of slice)
> * Status modals respond accordingly and show the proper information
> 
> **What did not pass testing:**
> 
> 1. User on /dough-staking with no wallet logged can't see the  Key Stats counting down. It starts when the user is connected
>    https://www.loom.com/share/2d371c5939cf49a3b9a5132e6b4de42e
> 2. In /piefolio the governance information is not updated, it is currently showing closed votes only from october (same un mainnet)
>    image
> 3. Your holding numbers are shown Green even though they are negative
>    image

@AdrianAddesso point 1 is good as it is, there's nothing to refresh is no address is logged in :)
gonna work on the other points.

**Comment by TotoFullStackDev** [comment]
@AdrianAddesso all done, it's building :)
double check and let me know how that goes.

**Review by Alexintosh — APPROVED** [review]

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
Points 1 and 2 addressed.
Point 3: I see positive numbers shown in red, while is expected:

- positive = green
- negative = red

**Comment by TotoFullStackDev** [comment]
@AdrianAddesso fixed, please re-check it

**Review by AdrianAddesso — APPROVED** [review]
Approved

**Pull request merged**
