### PR TITLE
Feature/pie 463 - KPI Calculator inside the Staking Dugh Page

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Test coverage hasn't decreased

### CODE REVIEW

**Review by dimarconicola — CHANGES_REQUESTED** [review]
I get 0 KPI options with my staking. Does it do the calculation correctly?

**Comment by TotoFullStackDev** [comment]
> I get 0 KPI options with my staking. Does it do the calculation correctly?

yes it is, double check from here, using the function balanceOf and your address
https://etherscan.io/address/0x42b766EF2Be22930C66CD4e3F5E33F3F89f359BD#readContract
it will give you zero, so the final calculation is zero so far, but the formula is the one provided by Gabo.

**Comment by dimarconicola** [comment]
> > I get 0 KPI options with my staking. Does it do the calculation correctly?
> 
> yes it is, double check from here, using the function balanceOf and your address https://etherscan.io/address/0x42b766EF2Be22930C66CD4e3F5E33F3F89f359BD#readContract it will give you zero, so the final calculation is zero so far, but the formula is the one provided by Gabo.

cool so then let's wait a couple of days for the airdrop before merging so that:
- the calculation is going to be based on the effective tokens
- users won't see 0.00 DOUGH on the component

**Review by dimarconicola — APPROVED** [review]

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
Typo: please change

- Estimated UMA Kpi Options
to

- Estimated UMA KPI Options

**Comment by TotoFullStackDev** [comment]
> Typo: please change
> 
> * Estimated UMA Kpi Options
>   to
> * Estimated UMA KPI Options

@AdrianAddesso done :)

**Review by AdrianAddesso — APPROVED** [review]
Approved

**Pull request closed without merging**
