### PR TITLE
Feature/PIE-506

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Test coverage hasn't decreased

### CODE REVIEW

**Comment by dimarconicola** [comment]
Screenshot 2021-10-19 at 17 56 44


- summary is completely off, please check the results
- on the tot staking commitment, maybe it would be better to have everything 1% and 3 years 97% (so the other values are not empty)

**Comment by TotoFullStackDev** [comment]
> Screenshot 2021-10-19 at 17 56 44
> 
> * summary is completely off, please check the results
> * on the tot staking commitment, maybe it would be better to have everything 1% and 3 years 97% (so the other values are not empty)

@dimarconicola it should all by fixed now, please re-check and let me know!

**Comment by dimarconicola** [comment]
Still doesn't work
This is my simulation https://deploy-preview-253--nightly-pools-piedao.netlify.app/#/staking-simulator/4PMJId1hmo9eIb9WtTvC

When I started it took a while to load data (everything was 0 or empty)
After something like 30sec it loaded it
Then it loaded and I managed to create a simulation
However when saving and opening the permalink it only shows 0 for several minutes

**Review by dimarconicola — APPROVED** [review]
I've changed parameters multiple times, created multiple permalinks also starting from the same one, checked the data and it all works!

**Comment by TotoFullStackDev** [comment]
> I've changed parameters multiple times, created multiple permalinks also starting from the same one, checked the data and it all works!

happy to hear that :)

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
Can't test, the rewards simulator data is not loading

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
The data in the permalink is still not 100% accurate. The summary numbers are slightly different, but the most notorious change is on the Treasury Liquidity Field that changed from (original) 22.16MM to (permalink) 22.19MM

Disregard the feedback if these numbers change due to a dynamic nature.

[Simulator permalink.pdf](https://github.com/pie-dao/pools.piedao.org/files/7419542/Simulator.permalink.pdf)

**Comment by TotoFullStackDev** [comment]
> The data in the permalink is still not 100% accurate. The summary numbers are slightly different, but the most notorious change is on the Treasury Liquidity Field that changed from (original) 22.16MM to (permalink) 22.19MM
> 
> Disregard the feedback if these numbers change due to a dynamic nature.
> 
> [Simulator permalink.pdf](https://github.com/pie-dao/pools.piedao.org/files/7419542/Simulator.permalink.pdf)

@AdrianAddesso yes, these numbers change due to a dynamic nature. it's all good so far :)

**Review by AdrianAddesso — APPROVED** [review]
Approved

**Pull request merged**
