### PR TITLE
Feature/pie 491

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Test coverage hasn't decreased

### CODE REVIEW

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
**Wallet with Dough only that did not vote**
-**Message shown: 'No open votes'.**
 -- (1) The Dough was bought before the latest snapshot was open, so there're open votes which I'm eligible participate
-**Clicking on 'No open votes'**
-- (1) It reads 'No active votes' -> we should be consistent on the text
-- (2) There's no link to the page mentioned, which I assume is Snapshot
-- (3) Typo on 'odred', should be 'order'.

**Wallet with veDough only that did vote with Dough**
-**Message shown: 'You voted this month'**
-- (1) It should only consider eligible votes, and veDough voting is still not open
-- (2) According to the scope of this task, it should read 'You need to vote'
-**Clicking on 'You voted this month'**
-- (1) I suggest we change the text from 'You are eligible to claim next month rewards as you already voted on an open issue.' to 'You are eligible for next month's reward distribution as you participated on PieDAO governance through voting.'

**Wallet with no Dough or veDough**
-**Message shown: 'No open votes'.**
-- (1) Proposal to check if the user has veDough and in this case say 'You have no veDough'

**Comment by TotoFullStackDev** [comment]
> **Wallet with Dough only that did not vote** -**Message shown: 'No open votes'.** -- (1) The Dough was bought before the latest snapshot was open, so there're open votes which I'm eligible participate -**Clicking on 'No open votes'** -- (1) It reads 'No active votes' -> we should be consistent on the text -- (2) There's no link to the page mentioned, which I assume is Snapshot -- (3) Typo on 'odred', should be 'order'.

this is not correct, the active proposals are filtered starting from the 18th of this month, and the snapshot space will be a different one, so there is NO active proposal so far, meaning the value we show is correct.
Regarding the typo and the consistence, i'm on it :)

> 
> **Wallet with veDough only that did vote with Dough** -**Message shown: 'You voted this month'** -- (1) It should only consider eligible votes, and veDough voting is still not open -- (2) According to the scope of this task, it should read 'You need to vote' -**Clicking on 'You voted this month'** -- (1) I suggest we change the text from 'You are eligible to claim next month rewards as you already voted on an open issue.' to 'You are eligible for next month's reward distribution as you participated on PieDAO governance through voting.'

same as before, we shall consider filtering the votes from the 18th and on the new space, so i'll investigate it and fix.
Ping you back once done.

> 
> **Wallet with no Dough or veDough** -**Message shown: 'No open votes'.** -- (1) Proposal to check if the user has veDough and in this case say 'You have no veDough'

this might be redundant and not needed, @dimarconicola what do you think about that?

**Review by AdrianAddesso — APPROVED** [review]
Implemented changes are correctly implemented.
Suggested changes were not applied,yet it's not a show stopper for the approval.
Points not implemented were justified accordingly.
Approved.

**Comment by TotoFullStackDev** [comment]
@Alexintosh @dantop114 @AdrianAddesso 
we will merge this into prod after the 18th, so we will directly start using the new snapshot's space "piedao.eth"

**Comment by dimarconicola** [comment]
> 'You have no veDough'

the 'You have no veDough' makes no sense as you wouldn't have a "claim" functionality without veDOUGH anyways (aka nothing to claim).

Having 18th as reference date looks correct to me

**Review by dimarconicola — APPROVED** [review]
I tested it and it LGTM

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
Toto, as per the Snapshot merge, the only test case I can validate is the wallet with veDough that has not voted and the wallet with Dough that has no veDough.
Wallet with only Dough: no information shown, which is correct
Wallet with veDough with no votes: info text is accurate. Error when opening the ´You have to vote´CTA, see below

image

**Review by AdrianAddesso — APPROVED** [review]

**Review by dimarconicola — APPROVED** [review]
looks good to me

**Pull request merged**
