### PR TITLE
PIE-533 - fixed bug on piefolio mobile version

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Description
Mobile view

After connecting a wallet, on a mobile device, the Piefolio page does not load the data from Your Holdings or Wallet Allocation.

Additionally, there's a loading state that does not retrieve any data at all. (This also happens in Desktop)

##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

### CODE REVIEW

**Review by dimarconicola — COMMENTED** [review]
I've tried to connect from mobile. It opens raimbow wallet, I click on connect, it confirms it's connected but when returning to the browser it still shows "connect wallet"

**Comment by TotoFullStackDev** [comment]
> I've tried to connect from mobile. It opens raimbow wallet, I click on connect, it confirms it's connected but when returning to the browser it still shows "connect wallet"

we have another bug opened for this related to walletconnect, this bug is not related to this PR imho.

**Review by dimarconicola — APPROVED** [review]
I can perform the action you described on discord.

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
Changes look ok.
I noticed the veDough icon shown is not the correct one. Please adjust:
Current_ 
image

**Review by AdrianAddesso — APPROVED** [review]
Approved

**Pull request merged**
