### PR TITLE
Feature/pie 482

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Description
In order to test this, you need to manually go to 
[https://deploy-preview-250--nightly-pools-piedao.netlify.app/#/staking_reward_breakdown/1628240233224](https://deploy-preview-250--nightly-pools-piedao.netlify.app/#/staking_reward_breakdown/1628240233224)

because there is no rewards item to click on so far, and the only valid timestamp you can use to fetch dummy data from dummy snapshot is 1628240233224.

##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

### CODE REVIEW

**Comment by dimarconicola** [comment]
I'd do the header like this

Screenshot 2021-10-15 at 10 46 53

Typos to correct
N of proposals this months > N. of proposals this months
Participation Ration > Participation Ratio

**Comment by TotoFullStackDev** [comment]
> I'd do the header like this
> 
> Screenshot 2021-10-15 at 10 46 53
> 
> Typos to correct N of proposals this months > N. of proposals this months Participation Ration > Participation Ratio

all done @dimarconicola

**Review by dimarconicola — APPROVED** [review]
It looks good to me

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
Few changes

- ¨N. of proposals this months¨ to ¨N° of proposals this months¨
- ¨SLICE Ridistributed¨ to ¨SLICE Redistributed¨
- ¨Treasury Vaults Performances¨ to ¨Treasury Vaults Performance¨
- Adjust numbers to have the proper $ format
- Be consistent on the number of decimals being shown (eg.: WETH 123213.45 vs DeFi++ 12354.476)

**Comment by TotoFullStackDev** [comment]
> Few changes
> 
> * ¨N. of proposals this months¨ to ¨N° of proposals this months¨
> * ¨SLICE Ridistributed¨ to ¨SLICE Redistributed¨
> * ¨Treasury Vaults Performances¨ to ¨Treasury Vaults Performance¨
> * Adjust numbers to have the proper $ format
> * Be consistent on the number of decimals being shown (eg.: WETH 123213.45 vs DeFi++ 12354.476)

all done

**Review by AdrianAddesso — APPROVED** [review]
All changes implemented.
Approved.

**Pull request merged**
