### PR TITLE
Feature/pie 459 - KPI Options Landing Page

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

### CODE REVIEW

**Comment by dimarconicola** [comment]
@Chiptuttofuso 
Staking simulator page and token (dough) page have a KPI banner that was linking to the forum. Now it should link this newly created landing page

**Review by dimarconicola — CHANGES_REQUESTED** [review]
It's too buggy when resizing the window. I am not sure we should approve it like this.

**Comment by TotoFullStackDev** [comment]
> It's too buggy when resizing the window. I am not sure we should approve it like this.

let me check what we can do.

**Comment by TotoFullStackDev** [comment]
> @Chiptuttofuso Staking simulator page and token (dough) page have a KPI banner that was linking to the forum. Now it should link this newly created landing page

@dimarconicola DONE! :)

**Comment by AdrianAddesso** [comment]
URL to test https://deploy-preview-255--nightly-pools-piedao.netlify.app/#/kpi-options-campaign

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
1) Typo:
Current: if 15M DOUGH is staked by 30th March 2022
New: If 15M DOUGH are staked by March 30th, 2022

2) Typo: 
Current: Try our staking simulator here to estimate...
New: Try our staking simulator to estimate...

3) Align prize milestones
image

**Comment by Alexintosh** [comment]
do we want a link in the menu?
the progress bar is all full but it should be proportionally full

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
Points 1 and 2 were addressed. The point 3, regarding the alignment is pending. Please see below that the Dough word has to be in the same reading line (sorry for the padding suggestion, not sure if its the right way of doing it)

image

**Review by AdrianAddesso — APPROVED** [review]

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
@dimarconicola can you make a version of the banner that can be seen on mobile screens (below 589 px)

**Review by AdrianAddesso — APPROVED** [review]
Requested changes delivered.
Mobile version of the banner looks well on the homepage and Dough page.

**Review by dimarconicola — APPROVED** [review]
lgtm

**Pull request merged**
