### PR TITLE
PIE-401 - implemented unstake modal

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

### CODE REVIEW

**Review by dimarconicola — APPROVED** [review]
I tested it and it works fine for me

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
modal works well.
Minor text change:
- Current: Rewards you claimed so far
- New: rewards claimed to date

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
Copy is fine.
Bug: After 1m20s the data vanishes
image

**Comment by TotoFullStackDev** [comment]
@AdrianAddesso investigating it

**Comment by TotoFullStackDev** [comment]
@AdrianAddesso shall be fixed now, please double check!

**Review by AdrianAddesso — APPROVED** [review]
All changes implemented.
Approved.

**Pull request merged**
