### PR TITLE
Feature/pie 476 - SLICE unwrapping page and listing

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Checklist

- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Test coverage hasn't decreased

### CODE REVIEW

**Comment by Alexintosh** [comment]
SLICE should not appear under PieVaults page since it’s not a managed vault, it’s only a basket not a real pie.Please link it somewhere else.

**Comment by Alexintosh** [comment]
SLICE should not appear under PieVaults page since it’s not a managed vault, it’s only a basket not a real pie.Please link it somewhere else.

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
@Chiptuttofuso and @dimarconicola  following Alessio’s comment below, I suggest to do the following change to the UI

1. Remove Slice from PieVaults
2. Create a new category called 'Governance Mining'. Subtitle to read ‘Governance Mining Reward Pie’
3. Show Slice Under Governance Mining, and keep the link to the PIE page

image

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
Some isses to be fixed.
**Desktop view:**
A) Change the copy to 'Governance Mining'
B) Add a '-' in the buy column
image

Mobile view:
A) Tables are too close together. Use the same spacing as the other tables have
B) Underlying assets shown are not correct. Remove all, show only Slice
image

**Comment by TotoFullStackDev** [comment]
> Some isses to be fixed. **Desktop view:** A) Change the copy to 'Governance Mining' B) Add a '-' in the buy column image
> 
> Mobile view: A) Tables are too close together. Use the same spacing as the other tables have B) Underlying assets shown are not correct. Remove all, show only Slice image

this has been fixed, and merged into the new PR which includes all we need for slice release.

**Pull request merged**
