### PR TITLE
Feature/pie 476

### PR DESCRIPTION
**Pull request by TotoFullStackDev**
##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Test coverage hasn't decreased

### CODE REVIEW

**Comment by dimarconicola** [comment]
Pies list: https://deploy-preview-252--nightly-pools-piedao.netlify.app/#/pies 
You cannot buy SLICE so the buy button should not be there

Redeem: https://deploy-preview-252--nightly-pools-piedao.netlify.app/#/slice
When clicking on redeem it shows add liquidity instead

**Comment by TotoFullStackDev** [comment]
> Pies list: https://deploy-preview-252--nightly-pools-piedao.netlify.app/#/pies You cannot buy SLICE so the buy button should not be there
> 
> Redeem: https://deploy-preview-252--nightly-pools-piedao.netlify.app/#/slice When clicking on redeem it shows add liquidity instead

@dimarconicola all fixed, double check and approve if it's all good

**Comment by dimarconicola** [comment]
I had a look and looks good. However it does not make sense to merge this now.

**Comment by TotoFullStackDev** [comment]
> I had a look and looks good. However it does not make sense to merge this now.

if that's ok, please approve it.
we can decide when to merge, but at least have it "ready-to-be-merged" facilitate the process imho.

**Review by AdrianAddesso — CHANGES_REQUESTED** [review]
1) The exchange shows the possibility to swap slice for something else. I believe we said we would not make a market for that. Is that still the case?
- the page is /#/swap
2) In the slice page: The allocation % takes too long to load (pls check)
3) In the slice page: align the text with the icon
- image
4) In the slice page: Update the text in the summary
-   Current version: Inside SLICE your find protocol fees coming
-   New version: Inside SLICE you will find protocol fees coming

**Comment by TotoFullStackDev** [comment]
> 1. The exchange shows the possibility to swap slice for something else. I believe we said we would not make a market for that. Is that still the case?
> 
> * the page is /#/swap
> 
> 1. In the slice page: The allocation % takes too long to load (pls check)
> 2. In the slice page: align the text with the icon
> 
> * image
> 
> 1. In the slice page: Update the text in the summary
> 
> * Current version: Inside SLICE your find protocol fees coming
> * New version: Inside SLICE you will find protocol fees coming

1 - swap compoment - removed SLICE - DONE
2 - is loading fast to me, it doesn't depend directly from us, when fetching infos from outside sometimes we face slowdowns
3 - nothing to align, it is a component perfectly aligned, just a visual effect. this component is the same for all PIE.
4 - updated text in the summary as suggested

@AdrianAddesso please review those changes, and approve if it's all as expected.

**Comment by dimarconicola** [comment]
Did we drop the NAV alltogether?

**Comment by TotoFullStackDev** [comment]
> Did we drop the NAV alltogether?

@dimarconicola what do you mean?

**Review by AdrianAddesso — APPROVED** [review]
Changes approved

**Review by dimarconicola — APPROVED** [review]

**Pull request merged**
